### PR TITLE
Keep textures table in lua entity

### PR DESCRIPTION
**Pull request by taikedz**
Allows external mods to reference a mob's texture when looked up from `minetest.registered_entities` (useful for cloning a mob externally)

### CODE REVIEW

**Comment by tenplus1** [comment]
self.textures would only add the list of textures from mob data, but if you want to copy/clone the actual skin a mob is wearing then use the already existing self.base_texture

**Comment by taikedz** [comment]
It would be for cloning a mob definition - not an instantiated mob entity.... do your notes above still apply? I no not see the base_texture property in the lua table returned from minetest.registered_entities

**Comment by tenplus1** [comment]
self.base_texture is generated by the api, it takes the many textures within def.textures and selects one at random to become the actual mob's base texture.

**Comment by taikedz** [comment]
So the change I put in is indeed what i thought was necessary?

Will see if i can make it work differently if you prefer not to pull it in.

**Comment by tenplus1** [comment]
The change you made above would only return ALL of the mob textures, not the current one it's using.
I've updated the api.txt with some important internal variables you could use.

**Comment by taikedz** [comment]
Thats the point - i do want all the textures. Maybe some context:

Say a wild dragon is defined with 4 alternative textures.

I want to be able to have an npc counterpart, with the same variance of textures possible.

So i take the table defined in minetest.registered_entities, clone it, and tegister a new mob definition. I can also use the cloned definition to make further tweaks to my tame dragon definition whilst leaving the original wild one intact.

Does that clarify the intent better?

**Comment by taikedz** [comment]
This is an illustration the intent https://m.youtube.com/watch?v=36VhUWrMjQY

**Comment by tenplus1** [comment]
On further inspection self.textures is already in use within the mob api and contains the current texture active for when mob is an adult, child or has gotten textures set, so the above pull wouldn't work.  I have however added self.texture_list that would contain what you need.

**Comment by taikedz** [comment]
Fantastic that'll do me

Cheers

**Pull request closed without merging**
