### PR TITLE
Replace deprecated methods

### PR DESCRIPTION
**Pull request by AntumDeluge**
- 'setting_get' with 'settings:get'
- 'setting_getbool' with 'settings:get_bool'

### CODE REVIEW

**Comment by tenplus1** [comment]
I would love to replace them with newer functions but I also want to keep compatibility with previous versions of minetest at the same time...

**Comment by AntumDeluge** [comment]
Ya, if you want your master branch to be compatible with 0.4.15, wouldn't want to merge until after 0.4.16 release, as the new ['settings' object calls][l_settings] are not available.

[l_settings]: https://github.com/minetest/minetest/blob/43d1f375d18a2fbc547a9b4f23d1354d645856ca/src/script/lua_api/l_settings.cpp#L267

**Comment by AntumDeluge** [comment]
@tenplus1 0.4.16 was released, so this merge should be compatible now.

**Comment by tenplus1** [comment]
Many servers still run 0.4.14/15 so until they ALL upgrade to 0.4.16 I will stick with the old setting functions for now...  Compatibility is more important than new features.

**Pull request closed without merging**
