### PR TITLE
Compatibility for registering eggs with different mob prefix

### PR DESCRIPTION
**Pull request by AntumDeluge**
These changes allow registering an egg for a mob that does not use the prefix of the mod that is implementing it. Examples:

Previous functionality:
```
-- mod: mob_shark

-- Registering mob with different prefix works fine.
mobs:register_mob(":mobs:shark", {
...

-- But registering egg with different prefix fails.
mobs:register_egg("mobs:shark", description, background, addegg, no_creative)
...

-- Prefixing mob name with ":" to register egg succeeds, but results in unknown entity ":mobs:shark"
-- so egg will not spawn entity when used.
mobs:register_egg(":mobs:shark", description, background, addegg, no_creative)
```

With the new functionality, an egg can be registered with the custom mob name prefix with adding ":". The API checks the prefix against the currently loaded mod & adds a colon as necessary.

New functionality:
```
-- Register egg with custom prefix.
mobs:register_egg("mobs:shark", description, background, addegg, no_creative)
```

Also fixes registering mobs not using standard naming convention.

### CODE REVIEW

**Comment by tenplus1** [comment]
I feel that adding this will make modders lazy when it comes to registering mobs under different mod names (mobs:shark) and I'd rather they use the actual mod name it resides in to register them instead (mobs_shark:shark), especially if two different mods try to use the same name.

**Comment by AntumDeluge** [comment]
Okay, but from my experience, the eggs do not work.

**Comment by tenplus1** [comment]
Don't work in what way ?

**Comment by AntumDeluge** [comment]
So, if I create a mod called ***mob_frog***, but want the in-game name to be ***mobs:frog***, I can register the mob with the colon prefix. But, if I try to register the egg with the colon prefix, there is an ***unknown entity*** error when I try to use the egg because it tries to spawn ***:mobs:frog***. And, I cannot register an egg without the colon prefix because of the name not matching the mod name.

I hope that makes sense:

Examples:
```
-- Successfully registers egg but cannot spawn entity
mobs.register_egg(":mobs:frog", def)
```
```
--- Registration fails because mob name prefix does not match mod name
mobs.register_egg("mobs:frog", def)
```

**Comment by AntumDeluge** [comment]
That was really the issue I was dealing with in this PR. I later decided to add the options to call ***register_mob*** without the colon prefix because I thought it would match egg registration & be less confusing.

**Comment by AntumDeluge** [comment]
My apologies, I didn't read your reply clearly. You were saying that you don't want the modders to use custom names. So, my response about the eggs not working doesn't fully apply to that.

However, I don't think it's wise to disallow modders to choose whether they use a custom name or not. It promotes ideology rather than "freedom".

At the very least, I think the eggs should be fixed so that they will work if the modder chooses to use a custom name. The only workaround that I could think of would be to use aliases, but I don't think aliases currently work with entities. Either way, I prefer the freedom to use a custom name.

**Pull request closed without merging**
