### PR TITLE
on_blast entity api sketch

### PR DESCRIPTION
**Pull request by sofar**
this is just an untested sketch

### CODE REVIEW

**Comment by tenplus1** [comment]
Ability to use on_blast added to api, immortal check shoudl be removed from tnt's entity_physics function though so that damage is dealt by default.

**Comment by sofar** [comment]
No, because that would erase all node drops. If you are immortal, you need to apply damage yourself.

**Comment by tenplus1** [comment]
Exactly my thinking, if immortal then use on_blast, which is why I would add it to builtin item drops to stop them being destroyed

**Comment by sofar** [comment]
that would push the TNT API into builtin, which isn't a good idea.

**Comment by tenplus1** [comment]
It's grown from what was a simple damage system to having to include a new blast damage system and knockback inside mobs api to compensate.

**Pull request closed without merging**
